baseURL = "http://www.enjoyread.club"
languageCode = "zh-cn"
title = "享读"
theme = "maupassant"
preserveTaxonomyNames = true
disablePathToLower = true

[author]
  name = "享读组成员"

[params]
  author = "享读"
  subtitle = "每周共读一本好书"
  busuanzi = true 

[menu]

  [[menu.main]]
    identifier = "members"
    name = "享读成员"
    url = "/members/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[permalinks]
  post = "/post/:filename/"

[params.utteranc]
    enable = true
    repo = "enjoylife520/blog-comment"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
